SportsStore/Models/ApplicationDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.DependencyInjection;

namespace SportsStore.Models
{
	public class ApplicationDbContext : DbContext
	{
		public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
			: base(options) { }
		public DbSet<Product> Products { get; set; }
	}
}

SportsStore/Models/EFProductRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Models
{
	public class EFProductRepository : IProductRepository
	{
		private ApplicationDbContext context;

		public EFProductRepository(ApplicationDbContext ctx)
		{
			context = ctx;
		}

		public IQueryable<Product> Products => context.Products;

	}
}

SportsStore/Models/FakeProductRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Models
{
	public class FakeProductRepository : IProductRepository
	{
		public IQueryable<Product> Products => new List<Product>
		{
			new Product {Name = "Football",Price = 25 },
			new Product {Name = "Football",Price = 25 },
			new Product {Name = "Football",Price = 25 }

		}.AsQueryable<Product>();
	}
}

SportsStore/Models/IProductRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Models
{
	public interface IProductRepository
	{
		IQueryable<Product> Products { get; }
	}
}

SportsStore/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Models
{
	public class Product
	{
		public int ProductID { get; set; }
		public string Name { get; set; }
		public string Description { get; set; }
		public decimal Price { get; set; }
		public string Category { get; set; }
	}
}

SportsStore/Models/SeedData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;

namespace SportsStore.Models
{
	public class SeedData
	{
		public static void EnsurePopulated(IApplicationBuilder app)
		{
			ApplicationDbContext context = app.ApplicationServices
				.GetRequiredService<ApplicationDbContext>();
			context.Database.Migrate();
			if (!context.Products.Any())
			{
				context.Products.AddRange(
					new Product
					{
						Name = "Kayak",
						Description = "A boat for one person",
						Category = "Watersports",
						Price = 275
					},
					new Product
					{
						Name = "Lifejacket",
						Description = "Protective and fashionable",
						Category = "Watersports",
						Price = 48.95m
					},
					new Product
					{
						Name = "Soccer Ball",
						Description = "FIFA-approved size and weight",
						Category = "Soccer",
						Price = 19.50m
					},
					new Product
					{
						Name = "Corner Flags",
						Description = "Give your playing field a professional touch",
						Category = "Soccer",
						Price = 34.95m
					},
					new Product
					{
						Name = "Stadium",
						Description = "Flat-packed 35,000-seat stadium",
						Category = "Soccer",
						Price = 79500
					},
					new Product
					{
						Name = "Thinking Cap",
						Description = "Improve brain efficiency by 75%",
						Category = "Chess",
						Price = 16
					},
					new Product
					{
						Name = "Unsteady Chair",
						Description = "Secretly give your opponent a disadvantage",
						Category = "Chess",
						Price = 29.95m
					},
					new Product
					{
						Name = "Human Chess Board",
						Description = "A fun game for the family",
						Category = "Chess",
						Price = 75
					},
					new Product
					{
						Name = "Bling-Bling King",
						Description = "Gold-plated, diamond-studded King",
						Category = "Chess",
						Price = 1200
					}
				);
				context.SaveChanges();
			}
		}

	}
}

SportsStore/Models/ViewModels/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Models.ViewModels
{
	public class PagingInfo
	{
		public int TotalItems { get; set; }
		public int ItemsPerPage { get; set; }
		public int CurrentPage { get; set; }

		public int TotalPages =>
			(int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
	}
}

SportsStore/Components/NavigationMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;


namespace SportsStore.Components
{
	public class NavigationMenuViewComponent : ViewComponent
	{
		private IProductRepository repository;
		public NavigationMenuViewComponent(IProductRepository repo)
		{
			repository = repo;
		}
		public IViewComponentResult Invoke()
		{
			return View(repository.Products
				.Select(x => x.Category)
				.Distinct()
				.OrderBy(x => x));
		}
	}
}

SportsStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using SportsStore.Models.ViewModels;
namespace SportsStore.Controllers
{
	public class ProductController : Controller
	{
		private IProductRepository repository;
		public int PageSize = 4;
		public ProductController(IProductRepository repo)
		{
			repository = repo;
		}
		public ViewResult List(string category,int productPage = 1)
			=> View(new ProductsListViewModel
			{
				Products = repository.Products
				.Where(p => category == null || p.Category == category)
					.OrderBy(p => p.ProductID)
					.Skip((productPage - 1) * PageSize)
					.Take(PageSize),
				PagingInfo = new PagingInfo
				{
					CurrentPage = productPage,
					ItemsPerPage = PageSize,
					TotalItems = repository.Products.Count()
				},
				CurrentCategory = category
			});
	}
}

SportsStore/Views/Product/List.cshtml
@model ProductsListViewModel

@foreach (var p in Model.Products)
{
    @Html.Partial("ProductSummary", p)
  
}

<div page-model="@Model.PagingInfo" page-action="List" page-classes-enabled="true"
     page-class="btn" page-class-normal="btn-secondary"
     page-class-selected="btn-primary" page-url-category="@Model.CurrentCategory" class ="btn-group pull-right m-1">
</div>

SportsStore/Views/Shared/Components/NavigationMenu/Default.cshtml
@model IEnumerable<string>

<a class="btn btn-block btn-secondary"
   asp-action="List"
   asp-controller="Product"
   asp-route-category="">
    Home
</a>

@foreach (string category in Model)
{
    <a class="btn btn-block btn-secondary"
       asp-action="List"
       asp-controller="Product"
       asp-route-category="@category"
       asp-route-productPage="1">
        @category
    </a>
}
    

SportsStore/Views/Shared/ProductSummary.cshtml
@model  Product

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>

    </div>
    <div class="card-text p-1">@Model.Description</div>
</div>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <title>SportsStore</title>
</head>
<body>
    <div class="navbar navbar-inverse bg-inverse" role="navigation">
        <a class="navbar-brand" href="#">SPORTS STORE</a>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>